removed unused routing , removed unused relationships , changed text …
ONSdigital/eq-census-schemas pull request #3
Opened 2018-07-10 15:27 UTC by AndrewTorrance

census armed forces test was falling over (500) with more than one user.  ( This led to an additional ticket on the backlog as it points to validator issues) 

Changes: 
Routing was attempting to go to a block in a different group , changed to go to the group and the target block was the first anyway,
relationship questions taken out
several cases of a when followed by another goto to the same target were removed (date of birth, date of birth1 and confirm dob)
Changed text on confirm date of birth answer so that it would match.

To test:- Run using quick launcher and validate that it supports multiple respondents and that routing works as expected

2018-07-11 08:21 UTC, kierenbeckett commented
https://preprod-new-surveys-launch.eq.ons.digital/quick-launch?url=https://raw.githubusercontent.com/ONSdigital/eq-census-schemas/cenus_armed_force_test/census_household.json

vs

https://preprod-new-surveys-launch.eq.ons.digital/quick-launch?url=https://raw.githubusercontent.com/ONSdigital/eq-census-schemas/cenus_armed_force_test2/census_household.json

@AndrewTorrance I'm struggling to reproduce the 500, perhaps you should show me the steps

2018-07-11 13:03 UTC, kierenbeckett commented
After further investigation the original schema causes 500s against what's on master but no what's in production (v2.50.0)

> [torrance] It came in when eq-2177 was merged in which is when we first started checking if a when dependency was outside a repeating group. Its blowing up in there. So I the schema error  went undetected until an apparently unconnected runner change .

2018-07-11 13:29 UTC, kierenbeckett approved these changes

2018-07-12 12:16 UTC, MebinAbraham approved these changes
Unable to reproduce 500 error.

2018-07-12 12:18 UTC, MebinAbraham requested changes
testing again.

2018-07-12 12:46 UTC, MebinAbraham approved these changes

2018-07-12 12:53 UTC, merged